# Generated by Django 4.2 on 2023-08-01 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_text', models.TextField(help_text='Введите текст напоминания', verbose_name='Текст напоминания')),
                ('reminder_days', models.PositiveIntegerField(default=0, help_text='Укажите через сколько дней отправлять напоминание', verbose_name='Интервал отправки в днях')),
                ('type', models.CharField(choices=[('first_reminder', 'Первое напоминание'), ('second_reminder', 'Второе напоминание')], help_text='Выберите тип напоминания', max_length=30, unique=True, verbose_name='Тип напоминания')),
                ('is_unsubscribe_button', models.BooleanField(default=False, help_text='Показать кнопку "Отписатьсся"?', verbose_name='Кнопка "Отписаться"')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['reminder_days'],
            },
        ),
        migrations.CreateModel(
            name='UserVk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='Введите индентификатор пользователя', verbose_name='Индентификатор пользователя')),
                ('first_name', models.CharField(help_text='Введите свое имя', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите свою фамилию', max_length=150, verbose_name='Фамилия')),
                ('city', models.CharField(blank=True, help_text='Введите свой город', max_length=150, verbose_name='Город')),
                ('birthday', models.DateField(blank=True, help_text='Введите дату дня рождения', null=True, verbose_name='День рождения')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите Ваш телефонный номер', max_length=128, region=None, verbose_name='Телефонный номер')),
                ('last_interaction', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего взаимодействия с ботом')),
                ('is_first_reminder_sent', models.BooleanField(default=False, help_text='Показывает, было ли отправлено первое напоминание', verbose_name='Первое напоминание отправлено')),
                ('is_second_reminder_sent', models.BooleanField(default=False, help_text='Показывает, было ли отправлено второе напоминание', verbose_name='Второе напоминание отправлено')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='VKToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(help_text='Введите индентификатор админа', unique=True, verbose_name='Индентификатор админа')),
                ('message_courses', models.TextField(help_text='Введите сообщение "О других направлениях"', verbose_name='Сообщение о других направлениях')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен ВК',
                'verbose_name_plural': 'Токены ВК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(blank=True, help_text='Введите тип сообщения', max_length=50, verbose_name='тип сообщения')),
                ('message', models.TextField(help_text='Введите сообщение, которое надо отправить', verbose_name='Сообщение пользователей')),
                ('vk_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания сообщения')),
                ('answered', models.BooleanField(blank=True, default=False, help_text='Если ответ прочитан, отметьте галочкой', verbose_name='состояние ответа')),
                ('uservk', models.ForeignKey(default=None, help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to='bot_app.uservk', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedelta', models.IntegerField(blank=True, help_text='Введите время между рассылками сообщений, в часах', verbose_name='Время между рассылками сообщений')),
                ('beginning_time', models.DateTimeField(blank=True, help_text='Введите дату и время начало рассылки сообщений', verbose_name='Дата и время начало рассылки сообщений')),
                ('time_end', models.DateTimeField(blank=True, help_text='Введите дату и время концарассылки сообщений', verbose_name='Дата и время конца рассылки сообщений')),
                ('message', models.ForeignKey(help_text='Выберите сообщение', on_delete=django.db.models.deletion.CASCADE, to='bot_app.message', verbose_name='сообщение')),
                ('uservk', models.ForeignKey(default=None, help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to='bot_app.uservk', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
