# Generated by Django 4.2 on 2023-08-02 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(default=123456, help_text='Введите индентификатор админа', unique=True, verbose_name='Индентификатор админа')),
                ('message_courses', models.TextField(default='tests', help_text='Введите сообщение "О других направлениях"', verbose_name='Сообщение о других направлениях')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные группы',
            },
        ),
        migrations.CreateModel(
            name='Mailing_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('Программирование для детей', 'Программирование для детей'), ('Робототехника', 'Робототехника')], default='Робототехника', help_text='Введите тип сообщения', max_length=30, verbose_name='тип сообщения')),
                ('message', models.TextField(help_text='Введите сообщение, которое надо отправить', verbose_name='Сообщение пользователей')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
                'ordering': ['message_type'],
            },
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='beginning_time',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='message',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='timedelta',
        ),
        migrations.AddField(
            model_name='mailing',
            name='counter',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество отправленных сообщений'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='type_mailing',
            field=models.CharField(choices=[('Программирование для детей', 'Программирование для детей'), ('Робототехника', 'Робототехника')], default='Программирование для детей', help_text='Введите тип рассылки', max_length=30, verbose_name='тип рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='uservk',
            field=models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to='bot_app.uservk', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, help_text='Введите сообщение, которое надо отправить', verbose_name='Сообщение пользователей'),
        ),
        migrations.AlterField(
            model_name='message',
            name='uservk',
            field=models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to='bot_app.uservk', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='uservk',
            name='city',
            field=models.CharField(blank=True, help_text='Введите свой город', max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='uservk',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите Ваш телефонный номер', max_length=128, null=True, region=None, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='uservk',
            name='user_id',
            field=models.IntegerField(help_text='Введите индентификатор пользователя', unique=True, verbose_name='Индентификатор пользователя'),
        ),
        migrations.DeleteModel(
            name='VKToken',
        ),
        migrations.AddField(
            model_name='mailing',
            name='messages',
            field=models.ManyToManyField(help_text='Выберите сообщения для рассылки', to='bot_app.mailing_message', verbose_name='Сообщение для рассылки'),
        ),
    ]
