# Generated by Django 4.2 on 2023-08-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_add_user_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservk',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Показывает, подписан ли пользователь на уведомления и рассылки', verbose_name='Подписка'),
        ),
    ]
