# Generated by Django 4.2 on 2023-08-05 09:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0005_alter_uservk_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservk',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='uservk',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Введите Ваш телефонный номер', max_length=128, null=True, region=None, verbose_name='Телефонный номер'),
        ),
    ]
