# Generated by Django 4.2 on 2023-08-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0007_alter_admindata_options_remove_admindata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessageForAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(help_text='Введите текст сообщения для рассылки', verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение для разовой рассылки',
                'verbose_name_plural': 'Сообщения для разовой рассылки',
            },
        ),
        migrations.AlterModelOptions(
            name='admindata',
            options={'verbose_name': 'Данные группы', 'verbose_name_plural': 'Данные группы'},
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_id',
            field=models.IntegerField(help_text='Введите индентификатор админа', unique=True, verbose_name='Индентификатор админа'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='message_courses',
            field=models.TextField(help_text='Введите сообщение "О других направлениях"', verbose_name='Сообщение о других направлениях'),
        ),
    ]
