# Generated by Django 4.2 on 2023-08-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0008_mailingmessageforall_alter_admindata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='type_mailing',
            field=models.CharField(choices=[('ПРОГРАММИРОВАНИЕ', 'ПРОГРАММИРОВАНИЕ'), ('РОБОТОТЕХНИКА', 'РОБОТОТЕХНИКА')], default='ПРОГРАММИРОВАНИЕ', help_text='Введите тип рассылки', max_length=30, verbose_name='тип рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing_message',
            name='message_type',
            field=models.CharField(choices=[('ПРОГРАММИРОВАНИЕ', 'ПРОГРАММИРОВАНИЕ'), ('РОБОТОТЕХНИКА', 'РОБОТОТЕХНИКА')], default='ПРОГРАММИРОВАНИЕ', help_text='Введите тип сообщения', max_length=30, verbose_name='тип сообщения'),
        ),
    ]
