# Generated by Django 4.2 on 2023-08-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0009_alter_mailing_type_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_activated',
            field=models.BooleanField(default=True, help_text='Показывает, подписан ли пользователь на  рассылку', verbose_name='Подписка на рассылку'),
        ),
        migrations.AddField(
            model_name='mailing_message',
            name='sorted',
            field=models.IntegerField(default=1, help_text='Введите номер, сообщения в очереди', verbose_name='Очередность сообщения'),
            preserve_default=False,
        ),
    ]
