# Generated by Django 4.2 on 2023-08-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0010_mailing_is_activated_mailing_message_sorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
