# Generated by Django 4.2 on 2023-08-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0011_admindata_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindata',
            name='message_courses',
        ),
    ]
