# Generated by Django 4.2 on 2023-08-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0012_remove_admindata_message_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Введите сообщение администратора', unique=True, verbose_name='Сообщение администратора')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Сообщение администратора',
                'verbose_name_plural': 'Сообщения администратора',
            },
        ),
        migrations.AlterModelOptions(
            name='admindata',
            options={'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы сообщества'},
        ),
        migrations.AlterField(
            model_name='admindata',
            name='admin_id',
            field=models.IntegerField(help_text='Введите индентификатор администратора', unique=True, verbose_name='Индентификатор администратора'),
        ),
    ]
